# Generated by Django 5.0 on 2023-12-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='welcome to the homepage', max_length=100),
        ),
    ]
